spring.application.name=service

server.port=8085

#AuthenticationServer(Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/Verifier

#RabbitMQ For Event Driven
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


#PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/entrace_db

spring.datasource.username=postgres

spring.datasource.password=my_new_password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true